openapi: 3.0.3
info:
  title: Photos NG API
  description: API for managing albums and media in Photos NG application
  version: 1.0.0
  contact:
    name: Photos NG Team
servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.photos-ng.com
    description: Production server

paths:
  /api/v1/albums:
    get:
      summary: List all albums
      description: Retrieve a list of all albums
      operationId: listAlbums
      tags:
        - Albums
      parameters:
        - name: limit
          in: query
          description: Maximum number of albums to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of albums to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAlbumsResponse'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Create a new album
      description: Create a new album
      operationId: createAlbum
      tags:
        - Albums
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAlbumRequest'
      responses:
        '201':
          description: Album created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/albums/{id}:
    get:
      summary: Get album by ID
      description: Retrieve a specific album by its ID
      operationId: getAlbum
      tags:
        - Albums
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the album to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Update album by ID
      description: Update a specific album by its ID
      operationId: updateAlbum
      tags:
        - Albums
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the album to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAlbumRequest'
      responses:
        '200':
          description: Album updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Delete album by ID
      description: Delete a specific album by its ID
      operationId: deleteAlbum
      tags:
        - Albums
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the album to delete
          schema:
            type: string
      responses:
        '204':
          description: Album deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/albums/{id}/sync:
    post:
      summary: Sync album
      description: Synchronize an album with the file system
      operationId: syncAlbum
      tags:
        - Albums
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the album to sync
          schema:
            type: string
      responses:
        '200':
          description: Album sync completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncAlbumResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/media:
    get:
      summary: List all media
      description: Retrieve a list of all media items
      operationId: listMedia
      tags:
        - Media
      parameters:
        - name: limit
          in: query
          description: Maximum number of media items to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of media items to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: album_id
          in: query
          description: Filter media by album ID
          required: false
          schema:
            type: string
        - name: type
          in: query
          description: Filter media by type
          required: false
          schema:
            type: string
            enum: [photo, video]
        - name: startDate
          in: query
          description: Filter media captured on or after this date
          required: false
          schema:
            type: string
            format: date
            pattern: '^\d{2}/\d{2}/\d{4}$'
            example: "01/01/2024"
        - name: endDate
          in: query
          description: Filter media captured on or before this date
          required: false
          schema:
            type: string
            format: date
            pattern: '^\d{2}/\d{2}/\d{4}$'
            example: "31/12/2024"
        - name: sortBy
          in: query
          description: Sort media by field
          required: false
          schema:
            type: string
            enum: [capturedAt, filename, type]
            default: capturedAt
        - name: sortOrder
          in: query
          description: Sort order
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListMediaResponse'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/media/{id}:
    get:
      summary: Get media by ID
      description: Retrieve a specific media item by its ID
      operationId: getMedia
      tags:
        - Media
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the media item to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Update media by ID
      description: Update a specific media item by its ID
      operationId: updateMedia
      tags:
        - Media
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the media item to update
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMediaRequest'
      responses:
        '200':
          description: Media updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Delete media by ID
      description: Delete a specific media item by its ID
      operationId: deleteMedia
      tags:
        - Media
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the media item to delete
          schema:
            type: string
      responses:
        '204':
          description: Media deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/media/{id}/thumbnail:
    get:
      summary: Get media thumbnail
      description: Retrieve the thumbnail image for a media item
      operationId: getMediaThumbnail
      tags:
        - Media
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the media item
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            image/*:
              schema:
                type: string
                format: binary
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/media/{id}/content:
    get:
      summary: Get media content
      description: Retrieve the full content of a media item
      operationId: getMediaContent
      tags:
        - Media
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the media item
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            image/*:
              schema:
                type: string
                format: binary
            video/*:
              schema:
                type: string
                format: binary
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/timeline:
    get:
      summary: Get timeline buckets
      description: Retrieve a timeline of media organized in buckets
      operationId: getTimeline
      tags:
        - Timeline
      parameters:
        - name: startDate
          in: query
          required: true
          description: Start date for the timeline
          schema:
            type: string
            format: date
            pattern: '^\d{2}/\d{2}/\d{4}$'
            example: "01/01/2024"
        - name: limit
          in: query
          description: Maximum number of buckets to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of buckets to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTimelineResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Album:
      type: object
      required:
        - id
        - href
        - name
        - path
      properties:
        id:
          type: string
          description: Unique identifier for the album
        href:
          type: string
          example: "/api/v1/albums/album_id"
        name:
          type: string
          description: name of the album
        path:
          type: string
          description: path of the folder on disk
        parentHref:
          type: string
          description: href of the parent
        description:
          type: string
        children:
          type: array
          items:
            type: object
            properties:
              href:
                type: string
              name:
                type: string
            required:
              - href
              - name
        media:
          type: array
          description: list of media href
          items:
            type: string

    Media:
      type: object
      properties:
        id:
          type: string
        href:
          type: string
          example: "/api/v1/media/some_id"
        albumHref:
          type: string
          example: "/api/v1/albums/album_id"
        capturedAt:
          type: string
          format: date
          pattern: '^\d{2}/\d{2}/\d{4}$'
          example: "01/01/2024"
        type:
          type: string
          example: "photo | video"
        filename:
          type: string
          description: full path of the media file on the disk
        thumbnail:
          type: string
          description: href to thumbnail
          example: "/api/v1/media/{id}/thumbnail"
        content:
          type: string
          description: href of the endpoint serving the content of the media
          example: "/api/v1/media/{id}/content"
        exif:
          type: array
          items:
            $ref: '#/components/schemas/ExifHeader'
      required:
        - id
        - href
        - albumHref
        - capturedAt
        - type
        - filename
        - thumbnail
        - content
        - exif

    ExifHeader:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
      required:
        - key
        - value

    Bucket:
      type: object
      properties:
        year:
          type: integer
        month:
          type: integer
        media:
          type: array
          description: list of media hrefs in this bucket
          items:
            type: string

    CreateAlbumRequest:
      type: object
      required:
        - name
      properties:
        parentId:
          type: string
          description: Id of the parent
        name:
          type: string
          description: Name of the album

    UpdateAlbumRequest:
      type: object
      description: Request body for updating an album
      properties:
        description:
          type: string
      required:
        - description


    UpdateMediaRequest:
      type: object
      properties:
        capturedAt:
          type: string
          format: date
          pattern: '^\d{2}/\d{2}/\d{4}$'
          description: Date when the media was captured
          example: "01/01/2024"
        exif:
          type: array
          items:
            $ref: '#/components/schemas/ExifHeader'
          description: EXIF data for the media

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details

    ListAlbumsResponse:
      type: object
      required:
        - albums
        - total
        - limit
        - offset
      properties:
        albums:
          type: array
          items:
            $ref: '#/components/schemas/Album'
        total:
          type: integer
          description: Total number of albums
        limit:
          type: integer
          description: Number of albums returned
        offset:
          type: integer
          description: Number of albums skipped

    ListMediaResponse:
      type: object
      required:
        - media
        - total
        - limit
        - offset
      properties:
        media:
          type: array
          items:
            $ref: '#/components/schemas/Media'
        total:
          type: integer
          description: Total number of media items
        limit:
          type: integer
          description: Number of media items returned
        offset:
          type: integer
          description: Number of media items skipped

    GetTimelineResponse:
      type: object
      required:
        - buckets
        - years
        - total
        - limit
        - offset
      properties:
        buckets:
          type: array
          items:
            $ref: '#/components/schemas/Bucket'
        years:
          type: array
          items:
            type: integer
          description: List of all years that contain photos
          example: [2020, 2021, 2022, 2023, 2024]
        total:
          type: integer
          description: Total number of buckets
        limit:
          type: integer
          description: Number of buckets returned
        offset:
          type: integer
          description: Number of buckets skipped

    SyncAlbumResponse:
      type: object
      required:
        - message
        - synced_items
      properties:
        message:
          type: string
          description: Sync completion message
          example: "Album sync completed"
        synced_items:
          type: integer
          description: Number of items synced
          example: 42

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Invalid request parameters"
            code: "BAD_REQUEST"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Album not found"
            code: "NOT_FOUND"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Internal server error"
            code: "INTERNAL_ERROR"
