// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Album defines model for Album.
type Album struct {
	// Id Unique identifier for the album
	Id openapi_types.UUID `json:"id"`
}

// CreateAlbumRequest Request body for creating a new album (currently no additional fields required)
type CreateAlbumRequest = map[string]interface{}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *string `json:"code,omitempty"`

	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Error message
	Message string `json:"message"`
}

// UpdateAlbumRequest Request body for updating an album (currently no additional fields to update)
type UpdateAlbumRequest = map[string]interface{}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListAlbumsParams defines parameters for ListAlbums.
type ListAlbumsParams struct {
	// Limit Maximum number of albums to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of albums to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAlbumJSONRequestBody defines body for CreateAlbum for application/json ContentType.
type CreateAlbumJSONRequestBody = CreateAlbumRequest

// UpdateAlbumJSONRequestBody defines body for UpdateAlbum for application/json ContentType.
type UpdateAlbumJSONRequestBody = UpdateAlbumRequest
