//go:build !optgen_ignore
// +build !optgen_ignore

// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package authz

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
)

type ListOptionsOption func(l *ListOptions)

// NewListOptionsWithOptions creates a new ListOptions with the passed in options set
func NewListOptionsWithOptions(opts ...ListOptionsOption) *ListOptions {
	l := &ListOptions{}
	for _, o := range opts {
		o(l)
	}
	return l
}

// NewListOptionsWithOptionsAndDefaults creates a new ListOptions with the passed in options set starting from the defaults
func NewListOptionsWithOptionsAndDefaults(opts ...ListOptionsOption) *ListOptions {
	l := &ListOptions{}
	defaults.MustSet(l)
	for _, o := range opts {
		o(l)
	}
	return l
}

// ToOption returns a new ListOptionsOption that sets the values from the passed in ListOptions
func (l *ListOptions) ToOption() ListOptionsOption {
	return func(to *ListOptions) {
		to.Limit = l.Limit
		to.Cursor = l.Cursor
	}
}

// DebugMap returns a map form of ListOptions for debugging
func (l *ListOptions) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["Limit"] = helpers.DebugValue(l.Limit, false)
	debugMap["Cursor"] = helpers.DebugValue(l.Cursor, false)
	return debugMap
}

// ListOptionsWithOptions configures an existing ListOptions with the passed in options set
func ListOptionsWithOptions(l *ListOptions, opts ...ListOptionsOption) *ListOptions {
	for _, o := range opts {
		o(l)
	}
	return l
}

// WithOptions configures the receiver ListOptions with the passed in options set
func (l *ListOptions) WithOptions(opts ...ListOptionsOption) *ListOptions {
	for _, o := range opts {
		o(l)
	}
	return l
}

// WithLimit returns an option that can set Limit on a ListOptions
func WithLimit(limit uint32) ListOptionsOption {
	return func(l *ListOptions) {
		l.Limit = limit
	}
}

// WithCursor returns an option that can set Cursor on a ListOptions
func WithCursor(cursor *string) ListOptionsOption {
	return func(l *ListOptions) {
		l.Cursor = cursor
	}
}
