// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: albums.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlbumsService_ListAlbums_FullMethodName  = "/photos_ng.api.v1.grpc.AlbumsService/ListAlbums"
	AlbumsService_CreateAlbum_FullMethodName = "/photos_ng.api.v1.grpc.AlbumsService/CreateAlbum"
	AlbumsService_GetAlbum_FullMethodName    = "/photos_ng.api.v1.grpc.AlbumsService/GetAlbum"
	AlbumsService_UpdateAlbum_FullMethodName = "/photos_ng.api.v1.grpc.AlbumsService/UpdateAlbum"
	AlbumsService_DeleteAlbum_FullMethodName = "/photos_ng.api.v1.grpc.AlbumsService/DeleteAlbum"
	AlbumsService_SyncAlbum_FullMethodName   = "/photos_ng.api.v1.grpc.AlbumsService/SyncAlbum"
)

// AlbumsServiceClient is the client API for AlbumsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Albums service definition
type AlbumsServiceClient interface {
	// List all albums with optional pagination and filtering
	ListAlbums(ctx context.Context, in *ListAlbumsRequest, opts ...grpc.CallOption) (*ListAlbumsResponse, error)
	// Create a new album
	CreateAlbum(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*Album, error)
	// Get a specific album by ID
	GetAlbum(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*Album, error)
	// Update a specific album by ID
	UpdateAlbum(ctx context.Context, in *UpdateAlbumByIdRequest, opts ...grpc.CallOption) (*Album, error)
	// Delete a specific album by ID
	DeleteAlbum(ctx context.Context, in *DeleteAlbumRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Sync an album with the file system
	SyncAlbum(ctx context.Context, in *SyncAlbumRequest, opts ...grpc.CallOption) (*SyncAlbumResponse, error)
}

type albumsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlbumsServiceClient(cc grpc.ClientConnInterface) AlbumsServiceClient {
	return &albumsServiceClient{cc}
}

func (c *albumsServiceClient) ListAlbums(ctx context.Context, in *ListAlbumsRequest, opts ...grpc.CallOption) (*ListAlbumsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlbumsResponse)
	err := c.cc.Invoke(ctx, AlbumsService_ListAlbums_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumsServiceClient) CreateAlbum(ctx context.Context, in *CreateAlbumRequest, opts ...grpc.CallOption) (*Album, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Album)
	err := c.cc.Invoke(ctx, AlbumsService_CreateAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumsServiceClient) GetAlbum(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*Album, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Album)
	err := c.cc.Invoke(ctx, AlbumsService_GetAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumsServiceClient) UpdateAlbum(ctx context.Context, in *UpdateAlbumByIdRequest, opts ...grpc.CallOption) (*Album, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Album)
	err := c.cc.Invoke(ctx, AlbumsService_UpdateAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumsServiceClient) DeleteAlbum(ctx context.Context, in *DeleteAlbumRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AlbumsService_DeleteAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *albumsServiceClient) SyncAlbum(ctx context.Context, in *SyncAlbumRequest, opts ...grpc.CallOption) (*SyncAlbumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncAlbumResponse)
	err := c.cc.Invoke(ctx, AlbumsService_SyncAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlbumsServiceServer is the server API for AlbumsService service.
// All implementations must embed UnimplementedAlbumsServiceServer
// for forward compatibility.
//
// Albums service definition
type AlbumsServiceServer interface {
	// List all albums with optional pagination and filtering
	ListAlbums(context.Context, *ListAlbumsRequest) (*ListAlbumsResponse, error)
	// Create a new album
	CreateAlbum(context.Context, *CreateAlbumRequest) (*Album, error)
	// Get a specific album by ID
	GetAlbum(context.Context, *GetAlbumRequest) (*Album, error)
	// Update a specific album by ID
	UpdateAlbum(context.Context, *UpdateAlbumByIdRequest) (*Album, error)
	// Delete a specific album by ID
	DeleteAlbum(context.Context, *DeleteAlbumRequest) (*emptypb.Empty, error)
	// Sync an album with the file system
	SyncAlbum(context.Context, *SyncAlbumRequest) (*SyncAlbumResponse, error)
	mustEmbedUnimplementedAlbumsServiceServer()
}

// UnimplementedAlbumsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlbumsServiceServer struct{}

func (UnimplementedAlbumsServiceServer) ListAlbums(context.Context, *ListAlbumsRequest) (*ListAlbumsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlbums not implemented")
}
func (UnimplementedAlbumsServiceServer) CreateAlbum(context.Context, *CreateAlbumRequest) (*Album, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlbum not implemented")
}
func (UnimplementedAlbumsServiceServer) GetAlbum(context.Context, *GetAlbumRequest) (*Album, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlbum not implemented")
}
func (UnimplementedAlbumsServiceServer) UpdateAlbum(context.Context, *UpdateAlbumByIdRequest) (*Album, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAlbum not implemented")
}
func (UnimplementedAlbumsServiceServer) DeleteAlbum(context.Context, *DeleteAlbumRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlbum not implemented")
}
func (UnimplementedAlbumsServiceServer) SyncAlbum(context.Context, *SyncAlbumRequest) (*SyncAlbumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncAlbum not implemented")
}
func (UnimplementedAlbumsServiceServer) mustEmbedUnimplementedAlbumsServiceServer() {}
func (UnimplementedAlbumsServiceServer) testEmbeddedByValue()                       {}

// UnsafeAlbumsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlbumsServiceServer will
// result in compilation errors.
type UnsafeAlbumsServiceServer interface {
	mustEmbedUnimplementedAlbumsServiceServer()
}

func RegisterAlbumsServiceServer(s grpc.ServiceRegistrar, srv AlbumsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAlbumsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlbumsService_ServiceDesc, srv)
}

func _AlbumsService_ListAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlbumsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).ListAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumsService_ListAlbums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).ListAlbums(ctx, req.(*ListAlbumsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumsService_CreateAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).CreateAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumsService_CreateAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).CreateAlbum(ctx, req.(*CreateAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumsService_GetAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).GetAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumsService_GetAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).GetAlbum(ctx, req.(*GetAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumsService_UpdateAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlbumByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).UpdateAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumsService_UpdateAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).UpdateAlbum(ctx, req.(*UpdateAlbumByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumsService_DeleteAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).DeleteAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumsService_DeleteAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).DeleteAlbum(ctx, req.(*DeleteAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlbumsService_SyncAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbumsServiceServer).SyncAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlbumsService_SyncAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbumsServiceServer).SyncAlbum(ctx, req.(*SyncAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlbumsService_ServiceDesc is the grpc.ServiceDesc for AlbumsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlbumsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "photos_ng.api.v1.grpc.AlbumsService",
	HandlerType: (*AlbumsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAlbums",
			Handler:    _AlbumsService_ListAlbums_Handler,
		},
		{
			MethodName: "CreateAlbum",
			Handler:    _AlbumsService_CreateAlbum_Handler,
		},
		{
			MethodName: "GetAlbum",
			Handler:    _AlbumsService_GetAlbum_Handler,
		},
		{
			MethodName: "UpdateAlbum",
			Handler:    _AlbumsService_UpdateAlbum_Handler,
		},
		{
			MethodName: "DeleteAlbum",
			Handler:    _AlbumsService_DeleteAlbum_Handler,
		},
		{
			MethodName: "SyncAlbum",
			Handler:    _AlbumsService_SyncAlbum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "albums.proto",
}
