// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: albums.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Album child reference
type AlbumChild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Href          string                 `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"` // Reference to child album
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Name of the child album
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumChild) Reset() {
	*x = AlbumChild{}
	mi := &file_albums_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumChild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumChild) ProtoMessage() {}

func (x *AlbumChild) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumChild.ProtoReflect.Descriptor instead.
func (*AlbumChild) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{0}
}

func (x *AlbumChild) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *AlbumChild) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Album message representing an album entity
type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // Unique identifier for the album
	Href          string                 `protobuf:"bytes,2,opt,name=href,proto3" json:"href,omitempty"`                                     // API reference to this album
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                     // Display name of the album
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                                     // File system path of the album
	ParentHref    *string                `protobuf:"bytes,5,opt,name=parent_href,json=parentHref,proto3,oneof" json:"parent_href,omitempty"` // Reference to parent album (if any)
	Thumbnail     *string                `protobuf:"bytes,6,opt,name=thumbnail,proto3,oneof" json:"thumbnail,omitempty"`                     // Reference to thumbnail image
	Description   *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`                 // Album description
	Children      []*AlbumChild          `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`                             // List of child album references
	MediaCount    int32                  `protobuf:"varint,9,opt,name=media_count,json=mediaCount,proto3" json:"media_count,omitempty"`      // Total media count including children
	Media         []string               `protobuf:"bytes,10,rep,name=media,proto3" json:"media,omitempty"`                                  // List of media references in this album
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_albums_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{1}
}

func (x *Album) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Album) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *Album) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Album) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Album) GetParentHref() string {
	if x != nil && x.ParentHref != nil {
		return *x.ParentHref
	}
	return ""
}

func (x *Album) GetThumbnail() string {
	if x != nil && x.Thumbnail != nil {
		return *x.Thumbnail
	}
	return ""
}

func (x *Album) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Album) GetChildren() []*AlbumChild {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Album) GetMediaCount() int32 {
	if x != nil {
		return x.MediaCount
	}
	return 0
}

func (x *Album) GetMedia() []string {
	if x != nil {
		return x.Media
	}
	return nil
}

// Request to create a new album
type CreateAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // Name of the album (required)
	ParentId      *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"` // ID of the parent album
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`           // Album description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbumRequest) Reset() {
	*x = CreateAlbumRequest{}
	mi := &file_albums_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumRequest) ProtoMessage() {}

func (x *CreateAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumRequest.ProtoReflect.Descriptor instead.
func (*CreateAlbumRequest) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAlbumRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlbumRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *CreateAlbumRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// Request to update an existing album
type UpdateAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   *string                `protobuf:"bytes,1,opt,name=description,proto3,oneof" json:"description,omitempty"` // Updated description
	Thumbnail     *string                `protobuf:"bytes,2,opt,name=thumbnail,proto3,oneof" json:"thumbnail,omitempty"`     // ID of the media to use as thumbnail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlbumRequest) Reset() {
	*x = UpdateAlbumRequest{}
	mi := &file_albums_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlbumRequest) ProtoMessage() {}

func (x *UpdateAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlbumRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlbumRequest) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAlbumRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateAlbumRequest) GetThumbnail() string {
	if x != nil && x.Thumbnail != nil {
		return *x.Thumbnail
	}
	return ""
}

// Request to list albums
type ListAlbumsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`                          // Pagination parameters
	WithParent    *bool                  `protobuf:"varint,2,opt,name=with_parent,json=withParent,proto3,oneof" json:"with_parent,omitempty"` // Include albums with parents (default: false)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlbumsRequest) Reset() {
	*x = ListAlbumsRequest{}
	mi := &file_albums_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlbumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlbumsRequest) ProtoMessage() {}

func (x *ListAlbumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlbumsRequest.ProtoReflect.Descriptor instead.
func (*ListAlbumsRequest) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{4}
}

func (x *ListAlbumsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListAlbumsRequest) GetWithParent() bool {
	if x != nil && x.WithParent != nil {
		return *x.WithParent
	}
	return false
}

// Response containing list of albums
type ListAlbumsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albums        []*Album               `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`         // List of albums
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"` // Pagination metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlbumsResponse) Reset() {
	*x = ListAlbumsResponse{}
	mi := &file_albums_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlbumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlbumsResponse) ProtoMessage() {}

func (x *ListAlbumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlbumsResponse.ProtoReflect.Descriptor instead.
func (*ListAlbumsResponse) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{5}
}

func (x *ListAlbumsResponse) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

func (x *ListAlbumsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Request to get a specific album by ID
type GetAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Album ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumRequest) Reset() {
	*x = GetAlbumRequest{}
	mi := &file_albums_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumRequest) ProtoMessage() {}

func (x *GetAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumRequest) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{6}
}

func (x *GetAlbumRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request to update a specific album by ID
type UpdateAlbumByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // Album ID
	Update        *UpdateAlbumRequest    `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"` // Update data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlbumByIdRequest) Reset() {
	*x = UpdateAlbumByIdRequest{}
	mi := &file_albums_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlbumByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlbumByIdRequest) ProtoMessage() {}

func (x *UpdateAlbumByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlbumByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlbumByIdRequest) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAlbumByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAlbumByIdRequest) GetUpdate() *UpdateAlbumRequest {
	if x != nil {
		return x.Update
	}
	return nil
}

// Request to delete a specific album by ID
type DeleteAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Album ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlbumRequest) Reset() {
	*x = DeleteAlbumRequest{}
	mi := &file_albums_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumRequest) ProtoMessage() {}

func (x *DeleteAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlbumRequest) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAlbumRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request to sync a specific album
type SyncAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Album ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAlbumRequest) Reset() {
	*x = SyncAlbumRequest{}
	mi := &file_albums_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAlbumRequest) ProtoMessage() {}

func (x *SyncAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAlbumRequest.ProtoReflect.Descriptor instead.
func (*SyncAlbumRequest) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{9}
}

func (x *SyncAlbumRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response for album sync operation
type SyncAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                             // Sync completion message
	SyncedItems   int32                  `protobuf:"varint,2,opt,name=synced_items,json=syncedItems,proto3" json:"synced_items,omitempty"` // Number of items synced
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAlbumResponse) Reset() {
	*x = SyncAlbumResponse{}
	mi := &file_albums_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAlbumResponse) ProtoMessage() {}

func (x *SyncAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAlbumResponse.ProtoReflect.Descriptor instead.
func (*SyncAlbumResponse) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{10}
}

func (x *SyncAlbumResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncAlbumResponse) GetSyncedItems() int32 {
	if x != nil {
		return x.SyncedItems
	}
	return 0
}

var File_albums_proto protoreflect.FileDescriptor

const file_albums_proto_rawDesc = "" +
	"\n" +
	"\falbums.proto\x12\x15photos_ng.api.v1.grpc\x1a\fcommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"4\n" +
	"\n" +
	"AlbumChild\x12\x12\n" +
	"\x04href\x18\x01 \x01(\tR\x04href\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe7\x02\n" +
	"\x05Album\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04href\x18\x02 \x01(\tR\x04href\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12$\n" +
	"\vparent_href\x18\x05 \x01(\tH\x00R\n" +
	"parentHref\x88\x01\x01\x12!\n" +
	"\tthumbnail\x18\x06 \x01(\tH\x01R\tthumbnail\x88\x01\x01\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x02R\vdescription\x88\x01\x01\x12=\n" +
	"\bchildren\x18\b \x03(\v2!.photos_ng.api.v1.grpc.AlbumChildR\bchildren\x12\x1f\n" +
	"\vmedia_count\x18\t \x01(\x05R\n" +
	"mediaCount\x12\x14\n" +
	"\x05media\x18\n" +
	" \x03(\tR\x05mediaB\x0e\n" +
	"\f_parent_hrefB\f\n" +
	"\n" +
	"_thumbnailB\x0e\n" +
	"\f_description\"\x8f\x01\n" +
	"\x12CreateAlbumRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\x0e\n" +
	"\f_description\"|\n" +
	"\x12UpdateAlbumRequest\x12%\n" +
	"\vdescription\x18\x01 \x01(\tH\x00R\vdescription\x88\x01\x01\x12!\n" +
	"\tthumbnail\x18\x02 \x01(\tH\x01R\tthumbnail\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_thumbnail\"\x93\x01\n" +
	"\x11ListAlbumsRequest\x12H\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2(.photos_ng.api.v1.grpc.PaginationRequestR\n" +
	"pagination\x12$\n" +
	"\vwith_parent\x18\x02 \x01(\bH\x00R\n" +
	"withParent\x88\x01\x01B\x0e\n" +
	"\f_with_parent\"\x95\x01\n" +
	"\x12ListAlbumsResponse\x124\n" +
	"\x06albums\x18\x01 \x03(\v2\x1c.photos_ng.api.v1.grpc.AlbumR\x06albums\x12I\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2).photos_ng.api.v1.grpc.PaginationResponseR\n" +
	"pagination\"!\n" +
	"\x0fGetAlbumRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"k\n" +
	"\x16UpdateAlbumByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\x06update\x18\x02 \x01(\v2).photos_ng.api.v1.grpc.UpdateAlbumRequestR\x06update\"$\n" +
	"\x12DeleteAlbumRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10SyncAlbumRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x11SyncAlbumResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\fsynced_items\x18\x02 \x01(\x05R\vsyncedItems2\xaa\x04\n" +
	"\rAlbumsService\x12a\n" +
	"\n" +
	"ListAlbums\x12(.photos_ng.api.v1.grpc.ListAlbumsRequest\x1a).photos_ng.api.v1.grpc.ListAlbumsResponse\x12V\n" +
	"\vCreateAlbum\x12).photos_ng.api.v1.grpc.CreateAlbumRequest\x1a\x1c.photos_ng.api.v1.grpc.Album\x12P\n" +
	"\bGetAlbum\x12&.photos_ng.api.v1.grpc.GetAlbumRequest\x1a\x1c.photos_ng.api.v1.grpc.Album\x12Z\n" +
	"\vUpdateAlbum\x12-.photos_ng.api.v1.grpc.UpdateAlbumByIdRequest\x1a\x1c.photos_ng.api.v1.grpc.Album\x12P\n" +
	"\vDeleteAlbum\x12).photos_ng.api.v1.grpc.DeleteAlbumRequest\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\tSyncAlbum\x12'.photos_ng.api.v1.grpc.SyncAlbumRequest\x1a(.photos_ng.api.v1.grpc.SyncAlbumResponseB\xce\x01\n" +
	"\x19com.photos_ng.api.v1.grpcB\vAlbumsProtoP\x01Z0git.tls.tupangiu.ro/cosmin/photos-ng/api/v1/grpc\xa2\x02\x04PAVG\xaa\x02\x14PhotosNg.Api.V1.Grpc\xca\x02\x14PhotosNg\\Api\\V1\\Grpc\xe2\x02 PhotosNg\\Api\\V1\\Grpc\\GPBMetadata\xea\x02\x17PhotosNg::Api::V1::Grpcb\x06proto3"

var (
	file_albums_proto_rawDescOnce sync.Once
	file_albums_proto_rawDescData []byte
)

func file_albums_proto_rawDescGZIP() []byte {
	file_albums_proto_rawDescOnce.Do(func() {
		file_albums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_albums_proto_rawDesc), len(file_albums_proto_rawDesc)))
	})
	return file_albums_proto_rawDescData
}

var file_albums_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_albums_proto_goTypes = []any{
	(*AlbumChild)(nil),             // 0: photos_ng.api.v1.grpc.AlbumChild
	(*Album)(nil),                  // 1: photos_ng.api.v1.grpc.Album
	(*CreateAlbumRequest)(nil),     // 2: photos_ng.api.v1.grpc.CreateAlbumRequest
	(*UpdateAlbumRequest)(nil),     // 3: photos_ng.api.v1.grpc.UpdateAlbumRequest
	(*ListAlbumsRequest)(nil),      // 4: photos_ng.api.v1.grpc.ListAlbumsRequest
	(*ListAlbumsResponse)(nil),     // 5: photos_ng.api.v1.grpc.ListAlbumsResponse
	(*GetAlbumRequest)(nil),        // 6: photos_ng.api.v1.grpc.GetAlbumRequest
	(*UpdateAlbumByIdRequest)(nil), // 7: photos_ng.api.v1.grpc.UpdateAlbumByIdRequest
	(*DeleteAlbumRequest)(nil),     // 8: photos_ng.api.v1.grpc.DeleteAlbumRequest
	(*SyncAlbumRequest)(nil),       // 9: photos_ng.api.v1.grpc.SyncAlbumRequest
	(*SyncAlbumResponse)(nil),      // 10: photos_ng.api.v1.grpc.SyncAlbumResponse
	(*PaginationRequest)(nil),      // 11: photos_ng.api.v1.grpc.PaginationRequest
	(*PaginationResponse)(nil),     // 12: photos_ng.api.v1.grpc.PaginationResponse
	(*emptypb.Empty)(nil),          // 13: google.protobuf.Empty
}
var file_albums_proto_depIdxs = []int32{
	0,  // 0: photos_ng.api.v1.grpc.Album.children:type_name -> photos_ng.api.v1.grpc.AlbumChild
	11, // 1: photos_ng.api.v1.grpc.ListAlbumsRequest.pagination:type_name -> photos_ng.api.v1.grpc.PaginationRequest
	1,  // 2: photos_ng.api.v1.grpc.ListAlbumsResponse.albums:type_name -> photos_ng.api.v1.grpc.Album
	12, // 3: photos_ng.api.v1.grpc.ListAlbumsResponse.pagination:type_name -> photos_ng.api.v1.grpc.PaginationResponse
	3,  // 4: photos_ng.api.v1.grpc.UpdateAlbumByIdRequest.update:type_name -> photos_ng.api.v1.grpc.UpdateAlbumRequest
	4,  // 5: photos_ng.api.v1.grpc.AlbumsService.ListAlbums:input_type -> photos_ng.api.v1.grpc.ListAlbumsRequest
	2,  // 6: photos_ng.api.v1.grpc.AlbumsService.CreateAlbum:input_type -> photos_ng.api.v1.grpc.CreateAlbumRequest
	6,  // 7: photos_ng.api.v1.grpc.AlbumsService.GetAlbum:input_type -> photos_ng.api.v1.grpc.GetAlbumRequest
	7,  // 8: photos_ng.api.v1.grpc.AlbumsService.UpdateAlbum:input_type -> photos_ng.api.v1.grpc.UpdateAlbumByIdRequest
	8,  // 9: photos_ng.api.v1.grpc.AlbumsService.DeleteAlbum:input_type -> photos_ng.api.v1.grpc.DeleteAlbumRequest
	9,  // 10: photos_ng.api.v1.grpc.AlbumsService.SyncAlbum:input_type -> photos_ng.api.v1.grpc.SyncAlbumRequest
	5,  // 11: photos_ng.api.v1.grpc.AlbumsService.ListAlbums:output_type -> photos_ng.api.v1.grpc.ListAlbumsResponse
	1,  // 12: photos_ng.api.v1.grpc.AlbumsService.CreateAlbum:output_type -> photos_ng.api.v1.grpc.Album
	1,  // 13: photos_ng.api.v1.grpc.AlbumsService.GetAlbum:output_type -> photos_ng.api.v1.grpc.Album
	1,  // 14: photos_ng.api.v1.grpc.AlbumsService.UpdateAlbum:output_type -> photos_ng.api.v1.grpc.Album
	13, // 15: photos_ng.api.v1.grpc.AlbumsService.DeleteAlbum:output_type -> google.protobuf.Empty
	10, // 16: photos_ng.api.v1.grpc.AlbumsService.SyncAlbum:output_type -> photos_ng.api.v1.grpc.SyncAlbumResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_albums_proto_init() }
func file_albums_proto_init() {
	if File_albums_proto != nil {
		return
	}
	file_common_proto_init()
	file_albums_proto_msgTypes[1].OneofWrappers = []any{}
	file_albums_proto_msgTypes[2].OneofWrappers = []any{}
	file_albums_proto_msgTypes[3].OneofWrappers = []any{}
	file_albums_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_albums_proto_rawDesc), len(file_albums_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_albums_proto_goTypes,
		DependencyIndexes: file_albums_proto_depIdxs,
		MessageInfos:      file_albums_proto_msgTypes,
	}.Build()
	File_albums_proto = out.File
	file_albums_proto_goTypes = nil
	file_albums_proto_depIdxs = nil
}
