// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: common.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Media type enumeration
type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_PHOTO       MediaType = 1
	MediaType_MEDIA_TYPE_VIDEO       MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_PHOTO",
		2: "MEDIA_TYPE_VIDEO",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_PHOTO":       1,
		"MEDIA_TYPE_VIDEO":       2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Sort order enumeration
type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASC         SortOrder = 1
	SortOrder_SORT_ORDER_DESC        SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// Media sort field enumeration
type MediaSortBy int32

const (
	MediaSortBy_MEDIA_SORT_BY_UNSPECIFIED MediaSortBy = 0
	MediaSortBy_MEDIA_SORT_BY_CAPTURED_AT MediaSortBy = 1
	MediaSortBy_MEDIA_SORT_BY_FILENAME    MediaSortBy = 2
	MediaSortBy_MEDIA_SORT_BY_TYPE        MediaSortBy = 3
)

// Enum value maps for MediaSortBy.
var (
	MediaSortBy_name = map[int32]string{
		0: "MEDIA_SORT_BY_UNSPECIFIED",
		1: "MEDIA_SORT_BY_CAPTURED_AT",
		2: "MEDIA_SORT_BY_FILENAME",
		3: "MEDIA_SORT_BY_TYPE",
	}
	MediaSortBy_value = map[string]int32{
		"MEDIA_SORT_BY_UNSPECIFIED": 0,
		"MEDIA_SORT_BY_CAPTURED_AT": 1,
		"MEDIA_SORT_BY_FILENAME":    2,
		"MEDIA_SORT_BY_TYPE":        3,
	}
)

func (x MediaSortBy) Enum() *MediaSortBy {
	p := new(MediaSortBy)
	*p = x
	return p
}

func (x MediaSortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaSortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (MediaSortBy) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x MediaSortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaSortBy.Descriptor instead.
func (MediaSortBy) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// Sync job status enumeration
type SyncJobStatus int32

const (
	SyncJobStatus_SYNC_JOB_STATUS_UNSPECIFIED SyncJobStatus = 0
	SyncJobStatus_SYNC_JOB_STATUS_PENDING     SyncJobStatus = 1
	SyncJobStatus_SYNC_JOB_STATUS_RUNNING     SyncJobStatus = 2
	SyncJobStatus_SYNC_JOB_STATUS_COMPLETED   SyncJobStatus = 3
	SyncJobStatus_SYNC_JOB_STATUS_FAILED      SyncJobStatus = 4
	SyncJobStatus_SYNC_JOB_STATUS_STOPPED     SyncJobStatus = 5
)

// Enum value maps for SyncJobStatus.
var (
	SyncJobStatus_name = map[int32]string{
		0: "SYNC_JOB_STATUS_UNSPECIFIED",
		1: "SYNC_JOB_STATUS_PENDING",
		2: "SYNC_JOB_STATUS_RUNNING",
		3: "SYNC_JOB_STATUS_COMPLETED",
		4: "SYNC_JOB_STATUS_FAILED",
		5: "SYNC_JOB_STATUS_STOPPED",
	}
	SyncJobStatus_value = map[string]int32{
		"SYNC_JOB_STATUS_UNSPECIFIED": 0,
		"SYNC_JOB_STATUS_PENDING":     1,
		"SYNC_JOB_STATUS_RUNNING":     2,
		"SYNC_JOB_STATUS_COMPLETED":   3,
		"SYNC_JOB_STATUS_FAILED":      4,
		"SYNC_JOB_STATUS_STOPPED":     5,
	}
)

func (x SyncJobStatus) Enum() *SyncJobStatus {
	p := new(SyncJobStatus)
	*p = x
	return p
}

func (x SyncJobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncJobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (SyncJobStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x SyncJobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncJobStatus.Descriptor instead.
func (SyncJobStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

// Task result item type enumeration
type TaskResultItemType int32

const (
	TaskResultItemType_TASK_RESULT_ITEM_TYPE_UNSPECIFIED TaskResultItemType = 0
	TaskResultItemType_TASK_RESULT_ITEM_TYPE_FILE        TaskResultItemType = 1
	TaskResultItemType_TASK_RESULT_ITEM_TYPE_FOLDER      TaskResultItemType = 2
)

// Enum value maps for TaskResultItemType.
var (
	TaskResultItemType_name = map[int32]string{
		0: "TASK_RESULT_ITEM_TYPE_UNSPECIFIED",
		1: "TASK_RESULT_ITEM_TYPE_FILE",
		2: "TASK_RESULT_ITEM_TYPE_FOLDER",
	}
	TaskResultItemType_value = map[string]int32{
		"TASK_RESULT_ITEM_TYPE_UNSPECIFIED": 0,
		"TASK_RESULT_ITEM_TYPE_FILE":        1,
		"TASK_RESULT_ITEM_TYPE_FOLDER":      2,
	}
)

func (x TaskResultItemType) Enum() *TaskResultItemType {
	p := new(TaskResultItemType)
	*p = x
	return p
}

func (x TaskResultItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskResultItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (TaskResultItemType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x TaskResultItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskResultItemType.Descriptor instead.
func (TaskResultItemType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

// Common error message structure
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// EXIF header for media metadata
type ExifHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExifHeader) Reset() {
	*x = ExifHeader{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExifHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExifHeader) ProtoMessage() {}

func (x *ExifHeader) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExifHeader.ProtoReflect.Descriptor instead.
func (*ExifHeader) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ExifHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExifHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Pagination parameters
type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // Maximum number of items to return (default: 20, max: 100)
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // Number of items to skip (default: 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Pagination response metadata
type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`   // Total number of items available
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // Number of items returned in this response
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // Number of items skipped
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Cursor-based pagination parameters for media endpoints
type CursorPaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`              // Maximum number of items to return (default: 20, max: 100)
	Cursor        *string                `protobuf:"bytes,2,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`       // Cursor for pagination (base64 encoded)
	Direction     *string                `protobuf:"bytes,3,opt,name=direction,proto3,oneof" json:"direction,omitempty"` // Direction: "forward" or "backward" (default: "forward")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorPaginationRequest) Reset() {
	*x = CursorPaginationRequest{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPaginationRequest) ProtoMessage() {}

func (x *CursorPaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPaginationRequest.ProtoReflect.Descriptor instead.
func (*CursorPaginationRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *CursorPaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CursorPaginationRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

func (x *CursorPaginationRequest) GetDirection() string {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return ""
}

// Cursor-based pagination response metadata for media endpoints
type CursorPaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`                                  // Number of items returned in this response
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"` // Cursor for the next page (if available)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorPaginationResponse) Reset() {
	*x = CursorPaginationResponse{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPaginationResponse) ProtoMessage() {}

func (x *CursorPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPaginationResponse.ProtoReflect.Descriptor instead.
func (*CursorPaginationResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *CursorPaginationResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CursorPaginationResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

// Task result status
type TaskResultStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*TaskResultStatus_Success
	//	*TaskResultStatus_Error
	Result        isTaskResultStatus_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultStatus) Reset() {
	*x = TaskResultStatus{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultStatus) ProtoMessage() {}

func (x *TaskResultStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultStatus.ProtoReflect.Descriptor instead.
func (*TaskResultStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResultStatus) GetResult() isTaskResultStatus_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskResultStatus) GetSuccess() string {
	if x != nil {
		if x, ok := x.Result.(*TaskResultStatus_Success); ok {
			return x.Success
		}
	}
	return ""
}

func (x *TaskResultStatus) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*TaskResultStatus_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isTaskResultStatus_Result interface {
	isTaskResultStatus_Result()
}

type TaskResultStatus_Success struct {
	Success string `protobuf:"bytes,1,opt,name=success,proto3,oneof"` // "ok" for successful processing
}

type TaskResultStatus_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // Error message if processing failed
}

func (*TaskResultStatus_Success) isTaskResultStatus_Result() {}

func (*TaskResultStatus_Error) isTaskResultStatus_Result() {}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x15photos_ng.api.v1.grpc\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x01\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12C\n" +
	"\adetails\x18\x03 \x03(\v2).photos_ng.api.v1.grpc.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\n" +
	"ExifHeader\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"A\n" +
	"\x11PaginationRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"X\n" +
	"\x12PaginationResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x88\x01\n" +
	"\x17CursorPaginationRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x02 \x01(\tH\x00R\x06cursor\x88\x01\x01\x12!\n" +
	"\tdirection\x18\x03 \x01(\tH\x01R\tdirection\x88\x01\x01B\t\n" +
	"\a_cursorB\f\n" +
	"\n" +
	"_direction\"f\n" +
	"\x18CursorPaginationResponse\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"P\n" +
	"\x10TaskResultStatus\x12\x1a\n" +
	"\asuccess\x18\x01 \x01(\tH\x00R\asuccess\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result*S\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_PHOTO\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_VIDEO\x10\x02*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x02*\x7f\n" +
	"\vMediaSortBy\x12\x1d\n" +
	"\x19MEDIA_SORT_BY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MEDIA_SORT_BY_CAPTURED_AT\x10\x01\x12\x1a\n" +
	"\x16MEDIA_SORT_BY_FILENAME\x10\x02\x12\x16\n" +
	"\x12MEDIA_SORT_BY_TYPE\x10\x03*\xc2\x01\n" +
	"\rSyncJobStatus\x12\x1f\n" +
	"\x1bSYNC_JOB_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SYNC_JOB_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17SYNC_JOB_STATUS_RUNNING\x10\x02\x12\x1d\n" +
	"\x19SYNC_JOB_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16SYNC_JOB_STATUS_FAILED\x10\x04\x12\x1b\n" +
	"\x17SYNC_JOB_STATUS_STOPPED\x10\x05*}\n" +
	"\x12TaskResultItemType\x12%\n" +
	"!TASK_RESULT_ITEM_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTASK_RESULT_ITEM_TYPE_FILE\x10\x01\x12 \n" +
	"\x1cTASK_RESULT_ITEM_TYPE_FOLDER\x10\x02B\xce\x01\n" +
	"\x19com.photos_ng.api.v1.grpcB\vCommonProtoP\x01Z0git.tls.tupangiu.ro/cosmin/photos-ng/api/v1/grpc\xa2\x02\x04PAVG\xaa\x02\x14PhotosNg.Api.V1.Grpc\xca\x02\x14PhotosNg\\Api\\V1\\Grpc\xe2\x02 PhotosNg\\Api\\V1\\Grpc\\GPBMetadata\xea\x02\x17PhotosNg::Api::V1::Grpcb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_proto_goTypes = []any{
	(MediaType)(0),                   // 0: photos_ng.api.v1.grpc.MediaType
	(SortOrder)(0),                   // 1: photos_ng.api.v1.grpc.SortOrder
	(MediaSortBy)(0),                 // 2: photos_ng.api.v1.grpc.MediaSortBy
	(SyncJobStatus)(0),               // 3: photos_ng.api.v1.grpc.SyncJobStatus
	(TaskResultItemType)(0),          // 4: photos_ng.api.v1.grpc.TaskResultItemType
	(*Error)(nil),                    // 5: photos_ng.api.v1.grpc.Error
	(*ExifHeader)(nil),               // 6: photos_ng.api.v1.grpc.ExifHeader
	(*PaginationRequest)(nil),        // 7: photos_ng.api.v1.grpc.PaginationRequest
	(*PaginationResponse)(nil),       // 8: photos_ng.api.v1.grpc.PaginationResponse
	(*CursorPaginationRequest)(nil),  // 9: photos_ng.api.v1.grpc.CursorPaginationRequest
	(*CursorPaginationResponse)(nil), // 10: photos_ng.api.v1.grpc.CursorPaginationResponse
	(*TaskResultStatus)(nil),         // 11: photos_ng.api.v1.grpc.TaskResultStatus
	nil,                              // 12: photos_ng.api.v1.grpc.Error.DetailsEntry
}
var file_common_proto_depIdxs = []int32{
	12, // 0: photos_ng.api.v1.grpc.Error.details:type_name -> photos_ng.api.v1.grpc.Error.DetailsEntry
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[4].OneofWrappers = []any{}
	file_common_proto_msgTypes[5].OneofWrappers = []any{}
	file_common_proto_msgTypes[6].OneofWrappers = []any{
		(*TaskResultStatus_Success)(nil),
		(*TaskResultStatus_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
