// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: photos_ng.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_photos_ng_proto protoreflect.FileDescriptor

const file_photos_ng_proto_rawDesc = "" +
	"\n" +
	"\x0fphotos_ng.proto\x12\x15photos_ng.api.v1.grpc\x1a\falbums.proto\x1a\vmedia.proto\x1a\n" +
	"sync.proto\x1a\vstats.proto\x1a\x1bgoogle/protobuf/empty.proto2\xf6\x10\n" +
	"\x0fPhotosNGService\x12a\n" +
	"\n" +
	"ListAlbums\x12(.photos_ng.api.v1.grpc.ListAlbumsRequest\x1a).photos_ng.api.v1.grpc.ListAlbumsResponse\x12V\n" +
	"\vCreateAlbum\x12).photos_ng.api.v1.grpc.CreateAlbumRequest\x1a\x1c.photos_ng.api.v1.grpc.Album\x12P\n" +
	"\bGetAlbum\x12&.photos_ng.api.v1.grpc.GetAlbumRequest\x1a\x1c.photos_ng.api.v1.grpc.Album\x12Z\n" +
	"\vUpdateAlbum\x12-.photos_ng.api.v1.grpc.UpdateAlbumByIdRequest\x1a\x1c.photos_ng.api.v1.grpc.Album\x12P\n" +
	"\vDeleteAlbum\x12).photos_ng.api.v1.grpc.DeleteAlbumRequest\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\tSyncAlbum\x12'.photos_ng.api.v1.grpc.SyncAlbumRequest\x1a(.photos_ng.api.v1.grpc.SyncAlbumResponse\x12T\n" +
	"\tListMedia\x12'.photos_ng.api.v1.grpc.ListMediaRequest\x1a\x1c.photos_ng.api.v1.grpc.Media0\x01\x12V\n" +
	"\vUploadMedia\x12).photos_ng.api.v1.grpc.UploadMediaRequest\x1a\x1c.photos_ng.api.v1.grpc.Media\x12P\n" +
	"\bGetMedia\x12&.photos_ng.api.v1.grpc.GetMediaRequest\x1a\x1c.photos_ng.api.v1.grpc.Media\x12Z\n" +
	"\vUpdateMedia\x12-.photos_ng.api.v1.grpc.UpdateMediaByIdRequest\x1a\x1c.photos_ng.api.v1.grpc.Media\x12P\n" +
	"\vDeleteMedia\x12).photos_ng.api.v1.grpc.DeleteMediaRequest\x1a\x16.google.protobuf.Empty\x12o\n" +
	"\x11GetMediaThumbnail\x12/.photos_ng.api.v1.grpc.GetMediaThumbnailRequest\x1a).photos_ng.api.v1.grpc.BinaryDataResponse\x12j\n" +
	"\x0fGetMediaContent\x12-.photos_ng.api.v1.grpc.GetMediaContentRequest\x1a&.photos_ng.api.v1.grpc.BinaryDataChunk0\x01\x12a\n" +
	"\fStartSyncJob\x12'.photos_ng.api.v1.grpc.StartSyncRequest\x1a(.photos_ng.api.v1.grpc.StartSyncResponse\x12g\n" +
	"\fListSyncJobs\x12*.photos_ng.api.v1.grpc.ListSyncJobsRequest\x1a+.photos_ng.api.v1.grpc.ListSyncJobsResponse\x12V\n" +
	"\n" +
	"GetSyncJob\x12(.photos_ng.api.v1.grpc.GetSyncJobRequest\x1a\x1e.photos_ng.api.v1.grpc.SyncJob\x12v\n" +
	"\x11ActionAllSyncJobs\x12/.photos_ng.api.v1.grpc.ActionAllSyncJobsRequest\x1a0.photos_ng.api.v1.grpc.ActionAllSyncJobsResponse\x12j\n" +
	"\rActionSyncJob\x12+.photos_ng.api.v1.grpc.ActionSyncJobRequest\x1a,.photos_ng.api.v1.grpc.ActionSyncJobResponse\x12\x82\x01\n" +
	"\x15ClearFinishedSyncJobs\x123.photos_ng.api.v1.grpc.ClearFinishedSyncJobsRequest\x1a4.photos_ng.api.v1.grpc.ClearFinishedSyncJobsResponse\x12d\n" +
	"\vStopSyncJob\x12).photos_ng.api.v1.grpc.StopSyncJobRequest\x1a*.photos_ng.api.v1.grpc.StopSyncJobResponse\x12p\n" +
	"\x0fStopAllSyncJobs\x12-.photos_ng.api.v1.grpc.StopAllSyncJobsRequest\x1a..photos_ng.api.v1.grpc.StopAllSyncJobsResponse\x12X\n" +
	"\bGetStats\x12&.photos_ng.api.v1.grpc.GetStatsRequest\x1a$.photos_ng.api.v1.grpc.StatsResponseB\xd0\x01\n" +
	"\x19com.photos_ng.api.v1.grpcB\rPhotosNgProtoP\x01Z0git.tls.tupangiu.ro/cosmin/photos-ng/api/v1/grpc\xa2\x02\x04PAVG\xaa\x02\x14PhotosNg.Api.V1.Grpc\xca\x02\x14PhotosNg\\Api\\V1\\Grpc\xe2\x02 PhotosNg\\Api\\V1\\Grpc\\GPBMetadata\xea\x02\x17PhotosNg::Api::V1::Grpcb\x06proto3"

var file_photos_ng_proto_goTypes = []any{
	(*ListAlbumsRequest)(nil),             // 0: photos_ng.api.v1.grpc.ListAlbumsRequest
	(*CreateAlbumRequest)(nil),            // 1: photos_ng.api.v1.grpc.CreateAlbumRequest
	(*GetAlbumRequest)(nil),               // 2: photos_ng.api.v1.grpc.GetAlbumRequest
	(*UpdateAlbumByIdRequest)(nil),        // 3: photos_ng.api.v1.grpc.UpdateAlbumByIdRequest
	(*DeleteAlbumRequest)(nil),            // 4: photos_ng.api.v1.grpc.DeleteAlbumRequest
	(*SyncAlbumRequest)(nil),              // 5: photos_ng.api.v1.grpc.SyncAlbumRequest
	(*ListMediaRequest)(nil),              // 6: photos_ng.api.v1.grpc.ListMediaRequest
	(*UploadMediaRequest)(nil),            // 7: photos_ng.api.v1.grpc.UploadMediaRequest
	(*GetMediaRequest)(nil),               // 8: photos_ng.api.v1.grpc.GetMediaRequest
	(*UpdateMediaByIdRequest)(nil),        // 9: photos_ng.api.v1.grpc.UpdateMediaByIdRequest
	(*DeleteMediaRequest)(nil),            // 10: photos_ng.api.v1.grpc.DeleteMediaRequest
	(*GetMediaThumbnailRequest)(nil),      // 11: photos_ng.api.v1.grpc.GetMediaThumbnailRequest
	(*GetMediaContentRequest)(nil),        // 12: photos_ng.api.v1.grpc.GetMediaContentRequest
	(*StartSyncRequest)(nil),              // 13: photos_ng.api.v1.grpc.StartSyncRequest
	(*ListSyncJobsRequest)(nil),           // 14: photos_ng.api.v1.grpc.ListSyncJobsRequest
	(*GetSyncJobRequest)(nil),             // 15: photos_ng.api.v1.grpc.GetSyncJobRequest
	(*ActionAllSyncJobsRequest)(nil),      // 16: photos_ng.api.v1.grpc.ActionAllSyncJobsRequest
	(*ActionSyncJobRequest)(nil),          // 17: photos_ng.api.v1.grpc.ActionSyncJobRequest
	(*ClearFinishedSyncJobsRequest)(nil),  // 18: photos_ng.api.v1.grpc.ClearFinishedSyncJobsRequest
	(*StopSyncJobRequest)(nil),            // 19: photos_ng.api.v1.grpc.StopSyncJobRequest
	(*StopAllSyncJobsRequest)(nil),        // 20: photos_ng.api.v1.grpc.StopAllSyncJobsRequest
	(*GetStatsRequest)(nil),               // 21: photos_ng.api.v1.grpc.GetStatsRequest
	(*ListAlbumsResponse)(nil),            // 22: photos_ng.api.v1.grpc.ListAlbumsResponse
	(*Album)(nil),                         // 23: photos_ng.api.v1.grpc.Album
	(*emptypb.Empty)(nil),                 // 24: google.protobuf.Empty
	(*SyncAlbumResponse)(nil),             // 25: photos_ng.api.v1.grpc.SyncAlbumResponse
	(*Media)(nil),                         // 26: photos_ng.api.v1.grpc.Media
	(*BinaryDataResponse)(nil),            // 27: photos_ng.api.v1.grpc.BinaryDataResponse
	(*BinaryDataChunk)(nil),               // 28: photos_ng.api.v1.grpc.BinaryDataChunk
	(*StartSyncResponse)(nil),             // 29: photos_ng.api.v1.grpc.StartSyncResponse
	(*ListSyncJobsResponse)(nil),          // 30: photos_ng.api.v1.grpc.ListSyncJobsResponse
	(*SyncJob)(nil),                       // 31: photos_ng.api.v1.grpc.SyncJob
	(*ActionAllSyncJobsResponse)(nil),     // 32: photos_ng.api.v1.grpc.ActionAllSyncJobsResponse
	(*ActionSyncJobResponse)(nil),         // 33: photos_ng.api.v1.grpc.ActionSyncJobResponse
	(*ClearFinishedSyncJobsResponse)(nil), // 34: photos_ng.api.v1.grpc.ClearFinishedSyncJobsResponse
	(*StopSyncJobResponse)(nil),           // 35: photos_ng.api.v1.grpc.StopSyncJobResponse
	(*StopAllSyncJobsResponse)(nil),       // 36: photos_ng.api.v1.grpc.StopAllSyncJobsResponse
	(*StatsResponse)(nil),                 // 37: photos_ng.api.v1.grpc.StatsResponse
}
var file_photos_ng_proto_depIdxs = []int32{
	0,  // 0: photos_ng.api.v1.grpc.PhotosNGService.ListAlbums:input_type -> photos_ng.api.v1.grpc.ListAlbumsRequest
	1,  // 1: photos_ng.api.v1.grpc.PhotosNGService.CreateAlbum:input_type -> photos_ng.api.v1.grpc.CreateAlbumRequest
	2,  // 2: photos_ng.api.v1.grpc.PhotosNGService.GetAlbum:input_type -> photos_ng.api.v1.grpc.GetAlbumRequest
	3,  // 3: photos_ng.api.v1.grpc.PhotosNGService.UpdateAlbum:input_type -> photos_ng.api.v1.grpc.UpdateAlbumByIdRequest
	4,  // 4: photos_ng.api.v1.grpc.PhotosNGService.DeleteAlbum:input_type -> photos_ng.api.v1.grpc.DeleteAlbumRequest
	5,  // 5: photos_ng.api.v1.grpc.PhotosNGService.SyncAlbum:input_type -> photos_ng.api.v1.grpc.SyncAlbumRequest
	6,  // 6: photos_ng.api.v1.grpc.PhotosNGService.ListMedia:input_type -> photos_ng.api.v1.grpc.ListMediaRequest
	7,  // 7: photos_ng.api.v1.grpc.PhotosNGService.UploadMedia:input_type -> photos_ng.api.v1.grpc.UploadMediaRequest
	8,  // 8: photos_ng.api.v1.grpc.PhotosNGService.GetMedia:input_type -> photos_ng.api.v1.grpc.GetMediaRequest
	9,  // 9: photos_ng.api.v1.grpc.PhotosNGService.UpdateMedia:input_type -> photos_ng.api.v1.grpc.UpdateMediaByIdRequest
	10, // 10: photos_ng.api.v1.grpc.PhotosNGService.DeleteMedia:input_type -> photos_ng.api.v1.grpc.DeleteMediaRequest
	11, // 11: photos_ng.api.v1.grpc.PhotosNGService.GetMediaThumbnail:input_type -> photos_ng.api.v1.grpc.GetMediaThumbnailRequest
	12, // 12: photos_ng.api.v1.grpc.PhotosNGService.GetMediaContent:input_type -> photos_ng.api.v1.grpc.GetMediaContentRequest
	13, // 13: photos_ng.api.v1.grpc.PhotosNGService.StartSyncJob:input_type -> photos_ng.api.v1.grpc.StartSyncRequest
	14, // 14: photos_ng.api.v1.grpc.PhotosNGService.ListSyncJobs:input_type -> photos_ng.api.v1.grpc.ListSyncJobsRequest
	15, // 15: photos_ng.api.v1.grpc.PhotosNGService.GetSyncJob:input_type -> photos_ng.api.v1.grpc.GetSyncJobRequest
	16, // 16: photos_ng.api.v1.grpc.PhotosNGService.ActionAllSyncJobs:input_type -> photos_ng.api.v1.grpc.ActionAllSyncJobsRequest
	17, // 17: photos_ng.api.v1.grpc.PhotosNGService.ActionSyncJob:input_type -> photos_ng.api.v1.grpc.ActionSyncJobRequest
	18, // 18: photos_ng.api.v1.grpc.PhotosNGService.ClearFinishedSyncJobs:input_type -> photos_ng.api.v1.grpc.ClearFinishedSyncJobsRequest
	19, // 19: photos_ng.api.v1.grpc.PhotosNGService.StopSyncJob:input_type -> photos_ng.api.v1.grpc.StopSyncJobRequest
	20, // 20: photos_ng.api.v1.grpc.PhotosNGService.StopAllSyncJobs:input_type -> photos_ng.api.v1.grpc.StopAllSyncJobsRequest
	21, // 21: photos_ng.api.v1.grpc.PhotosNGService.GetStats:input_type -> photos_ng.api.v1.grpc.GetStatsRequest
	22, // 22: photos_ng.api.v1.grpc.PhotosNGService.ListAlbums:output_type -> photos_ng.api.v1.grpc.ListAlbumsResponse
	23, // 23: photos_ng.api.v1.grpc.PhotosNGService.CreateAlbum:output_type -> photos_ng.api.v1.grpc.Album
	23, // 24: photos_ng.api.v1.grpc.PhotosNGService.GetAlbum:output_type -> photos_ng.api.v1.grpc.Album
	23, // 25: photos_ng.api.v1.grpc.PhotosNGService.UpdateAlbum:output_type -> photos_ng.api.v1.grpc.Album
	24, // 26: photos_ng.api.v1.grpc.PhotosNGService.DeleteAlbum:output_type -> google.protobuf.Empty
	25, // 27: photos_ng.api.v1.grpc.PhotosNGService.SyncAlbum:output_type -> photos_ng.api.v1.grpc.SyncAlbumResponse
	26, // 28: photos_ng.api.v1.grpc.PhotosNGService.ListMedia:output_type -> photos_ng.api.v1.grpc.Media
	26, // 29: photos_ng.api.v1.grpc.PhotosNGService.UploadMedia:output_type -> photos_ng.api.v1.grpc.Media
	26, // 30: photos_ng.api.v1.grpc.PhotosNGService.GetMedia:output_type -> photos_ng.api.v1.grpc.Media
	26, // 31: photos_ng.api.v1.grpc.PhotosNGService.UpdateMedia:output_type -> photos_ng.api.v1.grpc.Media
	24, // 32: photos_ng.api.v1.grpc.PhotosNGService.DeleteMedia:output_type -> google.protobuf.Empty
	27, // 33: photos_ng.api.v1.grpc.PhotosNGService.GetMediaThumbnail:output_type -> photos_ng.api.v1.grpc.BinaryDataResponse
	28, // 34: photos_ng.api.v1.grpc.PhotosNGService.GetMediaContent:output_type -> photos_ng.api.v1.grpc.BinaryDataChunk
	29, // 35: photos_ng.api.v1.grpc.PhotosNGService.StartSyncJob:output_type -> photos_ng.api.v1.grpc.StartSyncResponse
	30, // 36: photos_ng.api.v1.grpc.PhotosNGService.ListSyncJobs:output_type -> photos_ng.api.v1.grpc.ListSyncJobsResponse
	31, // 37: photos_ng.api.v1.grpc.PhotosNGService.GetSyncJob:output_type -> photos_ng.api.v1.grpc.SyncJob
	32, // 38: photos_ng.api.v1.grpc.PhotosNGService.ActionAllSyncJobs:output_type -> photos_ng.api.v1.grpc.ActionAllSyncJobsResponse
	33, // 39: photos_ng.api.v1.grpc.PhotosNGService.ActionSyncJob:output_type -> photos_ng.api.v1.grpc.ActionSyncJobResponse
	34, // 40: photos_ng.api.v1.grpc.PhotosNGService.ClearFinishedSyncJobs:output_type -> photos_ng.api.v1.grpc.ClearFinishedSyncJobsResponse
	35, // 41: photos_ng.api.v1.grpc.PhotosNGService.StopSyncJob:output_type -> photos_ng.api.v1.grpc.StopSyncJobResponse
	36, // 42: photos_ng.api.v1.grpc.PhotosNGService.StopAllSyncJobs:output_type -> photos_ng.api.v1.grpc.StopAllSyncJobsResponse
	37, // 43: photos_ng.api.v1.grpc.PhotosNGService.GetStats:output_type -> photos_ng.api.v1.grpc.StatsResponse
	22, // [22:44] is the sub-list for method output_type
	0,  // [0:22] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_photos_ng_proto_init() }
func file_photos_ng_proto_init() {
	if File_photos_ng_proto != nil {
		return
	}
	file_albums_proto_init()
	file_media_proto_init()
	file_sync_proto_init()
	file_stats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_photos_ng_proto_rawDesc), len(file_photos_ng_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_photos_ng_proto_goTypes,
		DependencyIndexes: file_photos_ng_proto_depIdxs,
	}.Build()
	File_photos_ng_proto = out.File
	file_photos_ng_proto_goTypes = nil
	file_photos_ng_proto_depIdxs = nil
}
