// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: stats.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Application statistics
type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Years         []int32                `protobuf:"varint,1,rep,packed,name=years,proto3" json:"years,omitempty"`                      // List of years that contain media
	CountMedia    int32                  `protobuf:"varint,2,opt,name=count_media,json=countMedia,proto3" json:"count_media,omitempty"` // Total number of media items
	CountAlbum    int32                  `protobuf:"varint,3,opt,name=count_album,json=countAlbum,proto3" json:"count_album,omitempty"` // Total number of albums
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *StatsResponse) GetYears() []int32 {
	if x != nil {
		return x.Years
	}
	return nil
}

func (x *StatsResponse) GetCountMedia() int32 {
	if x != nil {
		return x.CountMedia
	}
	return 0
}

func (x *StatsResponse) GetCountAlbum() int32 {
	if x != nil {
		return x.CountAlbum
	}
	return 0
}

// Request to get application statistics
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

var File_stats_proto protoreflect.FileDescriptor

const file_stats_proto_rawDesc = "" +
	"\n" +
	"\vstats.proto\x12\x15photos_ng.api.v1.grpc\"g\n" +
	"\rStatsResponse\x12\x14\n" +
	"\x05years\x18\x01 \x03(\x05R\x05years\x12\x1f\n" +
	"\vcount_media\x18\x02 \x01(\x05R\n" +
	"countMedia\x12\x1f\n" +
	"\vcount_album\x18\x03 \x01(\x05R\n" +
	"countAlbum\"\x11\n" +
	"\x0fGetStatsRequest2h\n" +
	"\fStatsService\x12X\n" +
	"\bGetStats\x12&.photos_ng.api.v1.grpc.GetStatsRequest\x1a$.photos_ng.api.v1.grpc.StatsResponseB\xcd\x01\n" +
	"\x19com.photos_ng.api.v1.grpcB\n" +
	"StatsProtoP\x01Z0git.tls.tupangiu.ro/cosmin/photos-ng/api/v1/grpc\xa2\x02\x04PAVG\xaa\x02\x14PhotosNg.Api.V1.Grpc\xca\x02\x14PhotosNg\\Api\\V1\\Grpc\xe2\x02 PhotosNg\\Api\\V1\\Grpc\\GPBMetadata\xea\x02\x17PhotosNg::Api::V1::Grpcb\x06proto3"

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData []byte
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)))
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stats_proto_goTypes = []any{
	(*StatsResponse)(nil),   // 0: photos_ng.api.v1.grpc.StatsResponse
	(*GetStatsRequest)(nil), // 1: photos_ng.api.v1.grpc.GetStatsRequest
}
var file_stats_proto_depIdxs = []int32{
	1, // 0: photos_ng.api.v1.grpc.StatsService.GetStats:input_type -> photos_ng.api.v1.grpc.GetStatsRequest
	0, // 1: photos_ng.api.v1.grpc.StatsService.GetStats:output_type -> photos_ng.api.v1.grpc.StatsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
