// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: sync.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sync job action enumeration
type SyncJobAction int32

const (
	SyncJobAction_SYNC_JOB_ACTION_UNSPECIFIED SyncJobAction = 0
	SyncJobAction_SYNC_JOB_ACTION_STOP        SyncJobAction = 1
	SyncJobAction_SYNC_JOB_ACTION_RESUME      SyncJobAction = 2
)

// Enum value maps for SyncJobAction.
var (
	SyncJobAction_name = map[int32]string{
		0: "SYNC_JOB_ACTION_UNSPECIFIED",
		1: "SYNC_JOB_ACTION_STOP",
		2: "SYNC_JOB_ACTION_RESUME",
	}
	SyncJobAction_value = map[string]int32{
		"SYNC_JOB_ACTION_UNSPECIFIED": 0,
		"SYNC_JOB_ACTION_STOP":        1,
		"SYNC_JOB_ACTION_RESUME":      2,
	}
)

func (x SyncJobAction) Enum() *SyncJobAction {
	p := new(SyncJobAction)
	*p = x
	return p
}

func (x SyncJobAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncJobAction) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_proto_enumTypes[0].Descriptor()
}

func (SyncJobAction) Type() protoreflect.EnumType {
	return &file_sync_proto_enumTypes[0]
}

func (x SyncJobAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncJobAction.Descriptor instead.
func (SyncJobAction) EnumDescriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

// Task result for sync operations
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          string                 `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`                                                                        // Name of the processed file/folder
	ItemType      TaskResultItemType     `protobuf:"varint,2,opt,name=item_type,json=itemType,proto3,enum=photos_ng.api.v1.grpc.TaskResultItemType" json:"item_type,omitempty"` // Type of item (file or folder)
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`                                                               // Processing time in milliseconds
	Result        *TaskResultStatus      `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`                                                                    // Result status (success or error)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *TaskResult) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *TaskResult) GetItemType() TaskResultItemType {
	if x != nil {
		return x.ItemType
	}
	return TaskResultItemType_TASK_RESULT_ITEM_TYPE_UNSPECIFIED
}

func (x *TaskResult) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TaskResult) GetResult() *TaskResultStatus {
	if x != nil {
		return x.Result
	}
	return nil
}

// Sync job information
type SyncJob struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                   // Unique identifier for the sync job
	Status         SyncJobStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=photos_ng.api.v1.grpc.SyncJobStatus" json:"status,omitempty"` // Current status of the sync job
	RemainingTasks int32                  `protobuf:"varint,3,opt,name=remaining_tasks,json=remainingTasks,proto3" json:"remaining_tasks,omitempty"`    // Number of files still to be processed
	TotalTasks     int32                  `protobuf:"varint,4,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`                // Total number of files to process
	CompletedTasks []*TaskResult          `protobuf:"bytes,5,rep,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`     // List of processed files with results
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                    // When the job was created
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`              // When the job started processing
	FinishedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at,omitempty"`           // When the job finished
	RemainingTime  *int32                 `protobuf:"varint,9,opt,name=remaining_time,json=remainingTime,proto3,oneof" json:"remaining_time,omitempty"` // Approximate remaining time in seconds
	Path           string                 `protobuf:"bytes,10,opt,name=path,proto3" json:"path,omitempty"`                                              // The folder path being synchronized
	Duration       *int32                 `protobuf:"varint,11,opt,name=duration,proto3,oneof" json:"duration,omitempty"`                               // Duration of the sync job in seconds
	Error          *string                `protobuf:"bytes,12,opt,name=error,proto3,oneof" json:"error,omitempty"`                                      // Error message if the job failed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncJob) Reset() {
	*x = SyncJob{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncJob) ProtoMessage() {}

func (x *SyncJob) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncJob.ProtoReflect.Descriptor instead.
func (*SyncJob) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncJob) GetStatus() SyncJobStatus {
	if x != nil {
		return x.Status
	}
	return SyncJobStatus_SYNC_JOB_STATUS_UNSPECIFIED
}

func (x *SyncJob) GetRemainingTasks() int32 {
	if x != nil {
		return x.RemainingTasks
	}
	return 0
}

func (x *SyncJob) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *SyncJob) GetCompletedTasks() []*TaskResult {
	if x != nil {
		return x.CompletedTasks
	}
	return nil
}

func (x *SyncJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SyncJob) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SyncJob) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *SyncJob) GetRemainingTime() int32 {
	if x != nil && x.RemainingTime != nil {
		return *x.RemainingTime
	}
	return 0
}

func (x *SyncJob) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SyncJob) GetDuration() int32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *SyncJob) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Request to start a new sync job
type StartSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // File system path to sync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSyncRequest) Reset() {
	*x = StartSyncRequest{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSyncRequest) ProtoMessage() {}

func (x *StartSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSyncRequest.ProtoReflect.Descriptor instead.
func (*StartSyncRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *StartSyncRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Response when starting a sync job
type StartSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier for the created sync job
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSyncResponse) Reset() {
	*x = StartSyncResponse{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSyncResponse) ProtoMessage() {}

func (x *StartSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSyncResponse.ProtoReflect.Descriptor instead.
func (*StartSyncResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *StartSyncResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request to list all sync jobs
type ListSyncJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncJobsRequest) Reset() {
	*x = ListSyncJobsRequest{}
	mi := &file_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncJobsRequest) ProtoMessage() {}

func (x *ListSyncJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncJobsRequest.ProtoReflect.Descriptor instead.
func (*ListSyncJobsRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

// Response containing list of sync jobs
type ListSyncJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*SyncJob             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"` // List of sync jobs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncJobsResponse) Reset() {
	*x = ListSyncJobsResponse{}
	mi := &file_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncJobsResponse) ProtoMessage() {}

func (x *ListSyncJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncJobsResponse.ProtoReflect.Descriptor instead.
func (*ListSyncJobsResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{5}
}

func (x *ListSyncJobsResponse) GetJobs() []*SyncJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// Request to get a specific sync job by ID
type GetSyncJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Sync job ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncJobRequest) Reset() {
	*x = GetSyncJobRequest{}
	mi := &file_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncJobRequest) ProtoMessage() {}

func (x *GetSyncJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncJobRequest.ProtoReflect.Descriptor instead.
func (*GetSyncJobRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{6}
}

func (x *GetSyncJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request to stop a specific sync job by ID
type StopSyncJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Sync job ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSyncJobRequest) Reset() {
	*x = StopSyncJobRequest{}
	mi := &file_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSyncJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSyncJobRequest) ProtoMessage() {}

func (x *StopSyncJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSyncJobRequest.ProtoReflect.Descriptor instead.
func (*StopSyncJobRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{7}
}

func (x *StopSyncJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response when stopping a sync job
type StopSyncJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`          // Success message
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // ID of the stopped job
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSyncJobResponse) Reset() {
	*x = StopSyncJobResponse{}
	mi := &file_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSyncJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSyncJobResponse) ProtoMessage() {}

func (x *StopSyncJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSyncJobResponse.ProtoReflect.Descriptor instead.
func (*StopSyncJobResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{8}
}

func (x *StopSyncJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StopSyncJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Request to stop all running sync jobs
type StopAllSyncJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAllSyncJobsRequest) Reset() {
	*x = StopAllSyncJobsRequest{}
	mi := &file_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAllSyncJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAllSyncJobsRequest) ProtoMessage() {}

func (x *StopAllSyncJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAllSyncJobsRequest.ProtoReflect.Descriptor instead.
func (*StopAllSyncJobsRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{9}
}

// Response when stopping all sync jobs
type StopAllSyncJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                // Success message
	StoppedCount  int32                  `protobuf:"varint,2,opt,name=stopped_count,json=stoppedCount,proto3" json:"stopped_count,omitempty"` // Number of jobs that were stopped
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAllSyncJobsResponse) Reset() {
	*x = StopAllSyncJobsResponse{}
	mi := &file_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAllSyncJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAllSyncJobsResponse) ProtoMessage() {}

func (x *StopAllSyncJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAllSyncJobsResponse.ProtoReflect.Descriptor instead.
func (*StopAllSyncJobsResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{10}
}

func (x *StopAllSyncJobsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StopAllSyncJobsResponse) GetStoppedCount() int32 {
	if x != nil {
		return x.StoppedCount
	}
	return 0
}

// Request to perform action on all sync jobs
type ActionAllSyncJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        SyncJobAction          `protobuf:"varint,1,opt,name=action,proto3,enum=photos_ng.api.v1.grpc.SyncJobAction" json:"action,omitempty"` // Action to perform (stop or resume)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionAllSyncJobsRequest) Reset() {
	*x = ActionAllSyncJobsRequest{}
	mi := &file_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionAllSyncJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionAllSyncJobsRequest) ProtoMessage() {}

func (x *ActionAllSyncJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionAllSyncJobsRequest.ProtoReflect.Descriptor instead.
func (*ActionAllSyncJobsRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{11}
}

func (x *ActionAllSyncJobsRequest) GetAction() SyncJobAction {
	if x != nil {
		return x.Action
	}
	return SyncJobAction_SYNC_JOB_ACTION_UNSPECIFIED
}

// Response when performing action on all sync jobs
type ActionAllSyncJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                         // Success message
	Action        SyncJobAction          `protobuf:"varint,2,opt,name=action,proto3,enum=photos_ng.api.v1.grpc.SyncJobAction" json:"action,omitempty"` // Action that was performed
	AffectedCount int32                  `protobuf:"varint,3,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"`       // Number of jobs affected by the action
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionAllSyncJobsResponse) Reset() {
	*x = ActionAllSyncJobsResponse{}
	mi := &file_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionAllSyncJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionAllSyncJobsResponse) ProtoMessage() {}

func (x *ActionAllSyncJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionAllSyncJobsResponse.ProtoReflect.Descriptor instead.
func (*ActionAllSyncJobsResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{12}
}

func (x *ActionAllSyncJobsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionAllSyncJobsResponse) GetAction() SyncJobAction {
	if x != nil {
		return x.Action
	}
	return SyncJobAction_SYNC_JOB_ACTION_UNSPECIFIED
}

func (x *ActionAllSyncJobsResponse) GetAffectedCount() int32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

// Request to perform action on a specific sync job
type ActionSyncJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                   // Sync job ID
	Action        SyncJobAction          `protobuf:"varint,2,opt,name=action,proto3,enum=photos_ng.api.v1.grpc.SyncJobAction" json:"action,omitempty"` // Action to perform (stop or resume)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSyncJobRequest) Reset() {
	*x = ActionSyncJobRequest{}
	mi := &file_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSyncJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSyncJobRequest) ProtoMessage() {}

func (x *ActionSyncJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSyncJobRequest.ProtoReflect.Descriptor instead.
func (*ActionSyncJobRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{13}
}

func (x *ActionSyncJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionSyncJobRequest) GetAction() SyncJobAction {
	if x != nil {
		return x.Action
	}
	return SyncJobAction_SYNC_JOB_ACTION_UNSPECIFIED
}

// Response when performing action on a specific sync job
type ActionSyncJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                         // Success message
	Action        SyncJobAction          `protobuf:"varint,2,opt,name=action,proto3,enum=photos_ng.api.v1.grpc.SyncJobAction" json:"action,omitempty"` // Action that was performed
	AffectedCount int32                  `protobuf:"varint,3,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"`       // Number of jobs affected by the action
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSyncJobResponse) Reset() {
	*x = ActionSyncJobResponse{}
	mi := &file_sync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSyncJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSyncJobResponse) ProtoMessage() {}

func (x *ActionSyncJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSyncJobResponse.ProtoReflect.Descriptor instead.
func (*ActionSyncJobResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{14}
}

func (x *ActionSyncJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionSyncJobResponse) GetAction() SyncJobAction {
	if x != nil {
		return x.Action
	}
	return SyncJobAction_SYNC_JOB_ACTION_UNSPECIFIED
}

func (x *ActionSyncJobResponse) GetAffectedCount() int32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

// Request to clear finished sync jobs
type ClearFinishedSyncJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearFinishedSyncJobsRequest) Reset() {
	*x = ClearFinishedSyncJobsRequest{}
	mi := &file_sync_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearFinishedSyncJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearFinishedSyncJobsRequest) ProtoMessage() {}

func (x *ClearFinishedSyncJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearFinishedSyncJobsRequest.ProtoReflect.Descriptor instead.
func (*ClearFinishedSyncJobsRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{15}
}

// Response when clearing finished sync jobs
type ClearFinishedSyncJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                // Success message
	ClearedCount  int32                  `protobuf:"varint,2,opt,name=cleared_count,json=clearedCount,proto3" json:"cleared_count,omitempty"` // Number of jobs that were cleared
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearFinishedSyncJobsResponse) Reset() {
	*x = ClearFinishedSyncJobsResponse{}
	mi := &file_sync_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearFinishedSyncJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearFinishedSyncJobsResponse) ProtoMessage() {}

func (x *ClearFinishedSyncJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearFinishedSyncJobsResponse.ProtoReflect.Descriptor instead.
func (*ClearFinishedSyncJobsResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{16}
}

func (x *ClearFinishedSyncJobsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClearFinishedSyncJobsResponse) GetClearedCount() int32 {
	if x != nil {
		return x.ClearedCount
	}
	return 0
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\x15photos_ng.api.v1.grpc\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x01\n" +
	"\n" +
	"TaskResult\x12\x12\n" +
	"\x04item\x18\x01 \x01(\tR\x04item\x12F\n" +
	"\titem_type\x18\x02 \x01(\x0e2).photos_ng.api.v1.grpc.TaskResultItemTypeR\bitemType\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12?\n" +
	"\x06result\x18\x04 \x01(\v2'.photos_ng.api.v1.grpc.TaskResultStatusR\x06result\"\xef\x04\n" +
	"\aSyncJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.photos_ng.api.v1.grpc.SyncJobStatusR\x06status\x12'\n" +
	"\x0fremaining_tasks\x18\x03 \x01(\x05R\x0eremainingTasks\x12\x1f\n" +
	"\vtotal_tasks\x18\x04 \x01(\x05R\n" +
	"totalTasks\x12J\n" +
	"\x0fcompleted_tasks\x18\x05 \x03(\v2!.photos_ng.api.v1.grpc.TaskResultR\x0ecompletedTasks\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartedAt\x88\x01\x01\x12@\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"finishedAt\x88\x01\x01\x12*\n" +
	"\x0eremaining_time\x18\t \x01(\x05H\x02R\rremainingTime\x88\x01\x01\x12\x12\n" +
	"\x04path\x18\n" +
	" \x01(\tR\x04path\x12\x1f\n" +
	"\bduration\x18\v \x01(\x05H\x03R\bduration\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\f \x01(\tH\x04R\x05error\x88\x01\x01B\r\n" +
	"\v_started_atB\x0e\n" +
	"\f_finished_atB\x11\n" +
	"\x0f_remaining_timeB\v\n" +
	"\t_durationB\b\n" +
	"\x06_error\"&\n" +
	"\x10StartSyncRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"#\n" +
	"\x11StartSyncResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13ListSyncJobsRequest\"J\n" +
	"\x14ListSyncJobsResponse\x122\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1e.photos_ng.api.v1.grpc.SyncJobR\x04jobs\"#\n" +
	"\x11GetSyncJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12StopSyncJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x13StopSyncJobResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"\x18\n" +
	"\x16StopAllSyncJobsRequest\"X\n" +
	"\x17StopAllSyncJobsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\rstopped_count\x18\x02 \x01(\x05R\fstoppedCount\"X\n" +
	"\x18ActionAllSyncJobsRequest\x12<\n" +
	"\x06action\x18\x01 \x01(\x0e2$.photos_ng.api.v1.grpc.SyncJobActionR\x06action\"\x9a\x01\n" +
	"\x19ActionAllSyncJobsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12<\n" +
	"\x06action\x18\x02 \x01(\x0e2$.photos_ng.api.v1.grpc.SyncJobActionR\x06action\x12%\n" +
	"\x0eaffected_count\x18\x03 \x01(\x05R\raffectedCount\"d\n" +
	"\x14ActionSyncJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\x06action\x18\x02 \x01(\x0e2$.photos_ng.api.v1.grpc.SyncJobActionR\x06action\"\x96\x01\n" +
	"\x15ActionSyncJobResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12<\n" +
	"\x06action\x18\x02 \x01(\x0e2$.photos_ng.api.v1.grpc.SyncJobActionR\x06action\x12%\n" +
	"\x0eaffected_count\x18\x03 \x01(\x05R\raffectedCount\"\x1e\n" +
	"\x1cClearFinishedSyncJobsRequest\"^\n" +
	"\x1dClearFinishedSyncJobsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\rcleared_count\x18\x02 \x01(\x05R\fclearedCount*f\n" +
	"\rSyncJobAction\x12\x1f\n" +
	"\x1bSYNC_JOB_ACTION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SYNC_JOB_ACTION_STOP\x10\x01\x12\x1a\n" +
	"\x16SYNC_JOB_ACTION_RESUME\x10\x022\xf2\x06\n" +
	"\vSyncService\x12a\n" +
	"\fStartSyncJob\x12'.photos_ng.api.v1.grpc.StartSyncRequest\x1a(.photos_ng.api.v1.grpc.StartSyncResponse\x12g\n" +
	"\fListSyncJobs\x12*.photos_ng.api.v1.grpc.ListSyncJobsRequest\x1a+.photos_ng.api.v1.grpc.ListSyncJobsResponse\x12V\n" +
	"\n" +
	"GetSyncJob\x12(.photos_ng.api.v1.grpc.GetSyncJobRequest\x1a\x1e.photos_ng.api.v1.grpc.SyncJob\x12v\n" +
	"\x11ActionAllSyncJobs\x12/.photos_ng.api.v1.grpc.ActionAllSyncJobsRequest\x1a0.photos_ng.api.v1.grpc.ActionAllSyncJobsResponse\x12j\n" +
	"\rActionSyncJob\x12+.photos_ng.api.v1.grpc.ActionSyncJobRequest\x1a,.photos_ng.api.v1.grpc.ActionSyncJobResponse\x12\x82\x01\n" +
	"\x15ClearFinishedSyncJobs\x123.photos_ng.api.v1.grpc.ClearFinishedSyncJobsRequest\x1a4.photos_ng.api.v1.grpc.ClearFinishedSyncJobsResponse\x12d\n" +
	"\vStopSyncJob\x12).photos_ng.api.v1.grpc.StopSyncJobRequest\x1a*.photos_ng.api.v1.grpc.StopSyncJobResponse\x12p\n" +
	"\x0fStopAllSyncJobs\x12-.photos_ng.api.v1.grpc.StopAllSyncJobsRequest\x1a..photos_ng.api.v1.grpc.StopAllSyncJobsResponseB\xcc\x01\n" +
	"\x19com.photos_ng.api.v1.grpcB\tSyncProtoP\x01Z0git.tls.tupangiu.ro/cosmin/photos-ng/api/v1/grpc\xa2\x02\x04PAVG\xaa\x02\x14PhotosNg.Api.V1.Grpc\xca\x02\x14PhotosNg\\Api\\V1\\Grpc\xe2\x02 PhotosNg\\Api\\V1\\Grpc\\GPBMetadata\xea\x02\x17PhotosNg::Api::V1::Grpcb\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_sync_proto_goTypes = []any{
	(SyncJobAction)(0),                    // 0: photos_ng.api.v1.grpc.SyncJobAction
	(*TaskResult)(nil),                    // 1: photos_ng.api.v1.grpc.TaskResult
	(*SyncJob)(nil),                       // 2: photos_ng.api.v1.grpc.SyncJob
	(*StartSyncRequest)(nil),              // 3: photos_ng.api.v1.grpc.StartSyncRequest
	(*StartSyncResponse)(nil),             // 4: photos_ng.api.v1.grpc.StartSyncResponse
	(*ListSyncJobsRequest)(nil),           // 5: photos_ng.api.v1.grpc.ListSyncJobsRequest
	(*ListSyncJobsResponse)(nil),          // 6: photos_ng.api.v1.grpc.ListSyncJobsResponse
	(*GetSyncJobRequest)(nil),             // 7: photos_ng.api.v1.grpc.GetSyncJobRequest
	(*StopSyncJobRequest)(nil),            // 8: photos_ng.api.v1.grpc.StopSyncJobRequest
	(*StopSyncJobResponse)(nil),           // 9: photos_ng.api.v1.grpc.StopSyncJobResponse
	(*StopAllSyncJobsRequest)(nil),        // 10: photos_ng.api.v1.grpc.StopAllSyncJobsRequest
	(*StopAllSyncJobsResponse)(nil),       // 11: photos_ng.api.v1.grpc.StopAllSyncJobsResponse
	(*ActionAllSyncJobsRequest)(nil),      // 12: photos_ng.api.v1.grpc.ActionAllSyncJobsRequest
	(*ActionAllSyncJobsResponse)(nil),     // 13: photos_ng.api.v1.grpc.ActionAllSyncJobsResponse
	(*ActionSyncJobRequest)(nil),          // 14: photos_ng.api.v1.grpc.ActionSyncJobRequest
	(*ActionSyncJobResponse)(nil),         // 15: photos_ng.api.v1.grpc.ActionSyncJobResponse
	(*ClearFinishedSyncJobsRequest)(nil),  // 16: photos_ng.api.v1.grpc.ClearFinishedSyncJobsRequest
	(*ClearFinishedSyncJobsResponse)(nil), // 17: photos_ng.api.v1.grpc.ClearFinishedSyncJobsResponse
	(TaskResultItemType)(0),               // 18: photos_ng.api.v1.grpc.TaskResultItemType
	(*TaskResultStatus)(nil),              // 19: photos_ng.api.v1.grpc.TaskResultStatus
	(SyncJobStatus)(0),                    // 20: photos_ng.api.v1.grpc.SyncJobStatus
	(*timestamppb.Timestamp)(nil),         // 21: google.protobuf.Timestamp
}
var file_sync_proto_depIdxs = []int32{
	18, // 0: photos_ng.api.v1.grpc.TaskResult.item_type:type_name -> photos_ng.api.v1.grpc.TaskResultItemType
	19, // 1: photos_ng.api.v1.grpc.TaskResult.result:type_name -> photos_ng.api.v1.grpc.TaskResultStatus
	20, // 2: photos_ng.api.v1.grpc.SyncJob.status:type_name -> photos_ng.api.v1.grpc.SyncJobStatus
	1,  // 3: photos_ng.api.v1.grpc.SyncJob.completed_tasks:type_name -> photos_ng.api.v1.grpc.TaskResult
	21, // 4: photos_ng.api.v1.grpc.SyncJob.created_at:type_name -> google.protobuf.Timestamp
	21, // 5: photos_ng.api.v1.grpc.SyncJob.started_at:type_name -> google.protobuf.Timestamp
	21, // 6: photos_ng.api.v1.grpc.SyncJob.finished_at:type_name -> google.protobuf.Timestamp
	2,  // 7: photos_ng.api.v1.grpc.ListSyncJobsResponse.jobs:type_name -> photos_ng.api.v1.grpc.SyncJob
	0,  // 8: photos_ng.api.v1.grpc.ActionAllSyncJobsRequest.action:type_name -> photos_ng.api.v1.grpc.SyncJobAction
	0,  // 9: photos_ng.api.v1.grpc.ActionAllSyncJobsResponse.action:type_name -> photos_ng.api.v1.grpc.SyncJobAction
	0,  // 10: photos_ng.api.v1.grpc.ActionSyncJobRequest.action:type_name -> photos_ng.api.v1.grpc.SyncJobAction
	0,  // 11: photos_ng.api.v1.grpc.ActionSyncJobResponse.action:type_name -> photos_ng.api.v1.grpc.SyncJobAction
	3,  // 12: photos_ng.api.v1.grpc.SyncService.StartSyncJob:input_type -> photos_ng.api.v1.grpc.StartSyncRequest
	5,  // 13: photos_ng.api.v1.grpc.SyncService.ListSyncJobs:input_type -> photos_ng.api.v1.grpc.ListSyncJobsRequest
	7,  // 14: photos_ng.api.v1.grpc.SyncService.GetSyncJob:input_type -> photos_ng.api.v1.grpc.GetSyncJobRequest
	12, // 15: photos_ng.api.v1.grpc.SyncService.ActionAllSyncJobs:input_type -> photos_ng.api.v1.grpc.ActionAllSyncJobsRequest
	14, // 16: photos_ng.api.v1.grpc.SyncService.ActionSyncJob:input_type -> photos_ng.api.v1.grpc.ActionSyncJobRequest
	16, // 17: photos_ng.api.v1.grpc.SyncService.ClearFinishedSyncJobs:input_type -> photos_ng.api.v1.grpc.ClearFinishedSyncJobsRequest
	8,  // 18: photos_ng.api.v1.grpc.SyncService.StopSyncJob:input_type -> photos_ng.api.v1.grpc.StopSyncJobRequest
	10, // 19: photos_ng.api.v1.grpc.SyncService.StopAllSyncJobs:input_type -> photos_ng.api.v1.grpc.StopAllSyncJobsRequest
	4,  // 20: photos_ng.api.v1.grpc.SyncService.StartSyncJob:output_type -> photos_ng.api.v1.grpc.StartSyncResponse
	6,  // 21: photos_ng.api.v1.grpc.SyncService.ListSyncJobs:output_type -> photos_ng.api.v1.grpc.ListSyncJobsResponse
	2,  // 22: photos_ng.api.v1.grpc.SyncService.GetSyncJob:output_type -> photos_ng.api.v1.grpc.SyncJob
	13, // 23: photos_ng.api.v1.grpc.SyncService.ActionAllSyncJobs:output_type -> photos_ng.api.v1.grpc.ActionAllSyncJobsResponse
	15, // 24: photos_ng.api.v1.grpc.SyncService.ActionSyncJob:output_type -> photos_ng.api.v1.grpc.ActionSyncJobResponse
	17, // 25: photos_ng.api.v1.grpc.SyncService.ClearFinishedSyncJobs:output_type -> photos_ng.api.v1.grpc.ClearFinishedSyncJobsResponse
	9,  // 26: photos_ng.api.v1.grpc.SyncService.StopSyncJob:output_type -> photos_ng.api.v1.grpc.StopSyncJobResponse
	11, // 27: photos_ng.api.v1.grpc.SyncService.StopAllSyncJobs:output_type -> photos_ng.api.v1.grpc.StopAllSyncJobsResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_common_proto_init()
	file_sync_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		EnumInfos:         file_sync_proto_enumTypes,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
