//go:build !optgen_ignore
// +build !optgen_ignore

// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package services

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
)

type ListOptionsOption func(l *ListOptions)

// NewListOptionsWithOptions creates a new ListOptions with the passed in options set
func NewListOptionsWithOptions(opts ...ListOptionsOption) *ListOptions {
	l := &ListOptions{}
	for _, o := range opts {
		o(l)
	}
	return l
}

// NewListOptionsWithOptionsAndDefaults creates a new ListOptions with the passed in options set starting from the defaults
func NewListOptionsWithOptionsAndDefaults(opts ...ListOptionsOption) *ListOptions {
	l := &ListOptions{}
	defaults.MustSet(l)
	for _, o := range opts {
		o(l)
	}
	return l
}

// ToOption returns a new ListOptionsOption that sets the values from the passed in ListOptions
func (l *ListOptions) ToOption() ListOptionsOption {
	return func(to *ListOptions) {
		to.Limit = l.Limit
		to.Offset = l.Offset
		to.ParentID = l.ParentID
		to.HasParent = l.HasParent
	}
}

// DebugMap returns a map form of ListOptions for debugging
func (l *ListOptions) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["Limit"] = helpers.DebugValue(l.Limit, false)
	debugMap["Offset"] = helpers.DebugValue(l.Offset, false)
	debugMap["ParentID"] = helpers.DebugValue(l.ParentID, false)
	debugMap["HasParent"] = helpers.DebugValue(l.HasParent, false)
	return debugMap
}

// ListOptionsWithOptions configures an existing ListOptions with the passed in options set
func ListOptionsWithOptions(l *ListOptions, opts ...ListOptionsOption) *ListOptions {
	for _, o := range opts {
		o(l)
	}
	return l
}

// WithOptions configures the receiver ListOptions with the passed in options set
func (l *ListOptions) WithOptions(opts ...ListOptionsOption) *ListOptions {
	for _, o := range opts {
		o(l)
	}
	return l
}

// WithLimit returns an option that can set Limit on a ListOptions
func WithLimit(limit int) ListOptionsOption {
	return func(l *ListOptions) {
		l.Limit = limit
	}
}

// WithOffset returns an option that can set Offset on a ListOptions
func WithOffset(offset int) ListOptionsOption {
	return func(l *ListOptions) {
		l.Offset = offset
	}
}

// WithParentID returns an option that can set ParentID on a ListOptions
func WithParentID(parentID *string) ListOptionsOption {
	return func(l *ListOptions) {
		l.ParentID = parentID
	}
}

// WithHasParent returns an option that can set HasParent on a ListOptions
func WithHasParent(hasParent bool) ListOptionsOption {
	return func(l *ListOptions) {
		l.HasParent = hasParent
	}
}
