//go:build !optgen_ignore
// +build !optgen_ignore

// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package services

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
)

type AlbumOptionsOption func(a *AlbumOptions)

// NewAlbumOptionsWithOptions creates a new AlbumOptions with the passed in options set
func NewAlbumOptionsWithOptions(opts ...AlbumOptionsOption) *AlbumOptions {
	a := &AlbumOptions{}
	for _, o := range opts {
		o(a)
	}
	return a
}

// NewAlbumOptionsWithOptionsAndDefaults creates a new AlbumOptions with the passed in options set starting from the defaults
func NewAlbumOptionsWithOptionsAndDefaults(opts ...AlbumOptionsOption) *AlbumOptions {
	a := &AlbumOptions{}
	defaults.MustSet(a)
	for _, o := range opts {
		o(a)
	}
	return a
}

// ToOption returns a new AlbumOptionsOption that sets the values from the passed in AlbumOptions
func (a *AlbumOptions) ToOption() AlbumOptionsOption {
	return func(to *AlbumOptions) {
		to.Limit = a.Limit
		to.Offset = a.Offset
		to.ParentID = a.ParentID
	}
}

// DebugMap returns a map form of AlbumOptions for debugging
func (a *AlbumOptions) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["Limit"] = helpers.DebugValue(a.Limit, false)
	debugMap["Offset"] = helpers.DebugValue(a.Offset, false)
	debugMap["ParentID"] = helpers.DebugValue(a.ParentID, false)
	return debugMap
}

// AlbumOptionsWithOptions configures an existing AlbumOptions with the passed in options set
func AlbumOptionsWithOptions(a *AlbumOptions, opts ...AlbumOptionsOption) *AlbumOptions {
	for _, o := range opts {
		o(a)
	}
	return a
}

// WithOptions configures the receiver AlbumOptions with the passed in options set
func (a *AlbumOptions) WithOptions(opts ...AlbumOptionsOption) *AlbumOptions {
	for _, o := range opts {
		o(a)
	}
	return a
}

// WithLimit returns an option that can set Limit on a AlbumOptions
func WithLimit(limit int) AlbumOptionsOption {
	return func(a *AlbumOptions) {
		a.Limit = limit
	}
}

// WithOffset returns an option that can set Offset on a AlbumOptions
func WithOffset(offset int) AlbumOptionsOption {
	return func(a *AlbumOptions) {
		a.Offset = offset
	}
}

// WithParentID returns an option that can set ParentID on a AlbumOptions
func WithParentID(parentID *string) AlbumOptionsOption {
	return func(a *AlbumOptions) {
		a.ParentID = parentID
	}
}
