//go:build !optgen_ignore
// +build !optgen_ignore

// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package config

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
)

type AuthenticationOption func(a *Authentication)

// NewAuthenticationWithOptions creates a new Authentication with the passed in options set
func NewAuthenticationWithOptions(opts ...AuthenticationOption) *Authentication {
	a := &Authentication{}
	for _, o := range opts {
		o(a)
	}
	return a
}

// NewAuthenticationWithOptionsAndDefaults creates a new Authentication with the passed in options set starting from the defaults
func NewAuthenticationWithOptionsAndDefaults(opts ...AuthenticationOption) *Authentication {
	a := &Authentication{}
	defaults.MustSet(a)
	for _, o := range opts {
		o(a)
	}
	return a
}

// ToOption returns a new AuthenticationOption that sets the values from the passed in Authentication
func (a *Authentication) ToOption() AuthenticationOption {
	return func(to *Authentication) {
		to.Enabled = a.Enabled
		to.WellknownURL = a.WellknownURL
		to.ClientID = a.ClientID
		to.ClientSecret = a.ClientSecret
	}
}

// DebugMap returns a map form of Authentication for debugging
func (a *Authentication) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["Enabled"] = helpers.DebugValue(a.Enabled, false)
	debugMap["WellknownURL"] = helpers.DebugValue(a.WellknownURL, false)
	debugMap["ClientID"] = helpers.DebugValue(a.ClientID, false)
	debugMap["ClientSecret"] = helpers.DebugValue(a.ClientSecret, false)
	return debugMap
}

// AuthenticationWithOptions configures an existing Authentication with the passed in options set
func AuthenticationWithOptions(a *Authentication, opts ...AuthenticationOption) *Authentication {
	for _, o := range opts {
		o(a)
	}
	return a
}

// WithOptions configures the receiver Authentication with the passed in options set
func (a *Authentication) WithOptions(opts ...AuthenticationOption) *Authentication {
	for _, o := range opts {
		o(a)
	}
	return a
}

// WithEnabled returns an option that can set Enabled on a Authentication
func WithEnabled(enabled bool) AuthenticationOption {
	return func(a *Authentication) {
		a.Enabled = enabled
	}
}

// WithWellknownURL returns an option that can set WellknownURL on a Authentication
func WithWellknownURL(wellknownURL string) AuthenticationOption {
	return func(a *Authentication) {
		a.WellknownURL = wellknownURL
	}
}

// WithClientID returns an option that can set ClientID on a Authentication
func WithClientID(clientID string) AuthenticationOption {
	return func(a *Authentication) {
		a.ClientID = clientID
	}
}

// WithClientSecret returns an option that can set ClientSecret on a Authentication
func WithClientSecret(clientSecret string) AuthenticationOption {
	return func(a *Authentication) {
		a.ClientSecret = clientSecret
	}
}
